Validate (Staging):
    image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
    stage: Source
    environment: Staging
    variables:
        ORG: "Capstone"
        ENV: "${CI_ENVIRONMENT_NAME}"
        CRT: "arn:aws:acm:us-east-1:700423713782:certificate/60d62f36-c2e1-4ece-be36-4f70736f7f70"
        ZNE: "pebblego.com"
    script:
        - export TF_ADDRESS="${TF_URI}/${CI_ENVIRONMENT_NAME}"
        -   |
            cat << EOF > .tfvars
            organization        = "${ORG}"
            environment         = "${ENV}"
            certificate         = "${CRT}"
            hosted-zone-fqdn    = "${ZNE}"
            EOF
        - cat .tfvars
        - export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_DEVELOPMENT}"
        - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}"
        - gitlab-terraform init || true
        - gitlab-terraform validate || true
        - gitlab-terraform refresh -var-file ".tfvars" || true
    allow_failure: True
    artifacts:
        paths: [ ".tfvars" ]

Plan (Staging):
    image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
    stage: Build
    environment: Staging
    needs:
        -   job: Validate (Staging)
            artifacts: True
    script:
        - export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_DEVELOPMENT}"
        - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}"
        - export TF_ADDRESS="${TF_URI}/${CI_ENVIRONMENT_NAME}"
        - gitlab-terraform plan --var-file ".tfvars"
        - gitlab-terraform plan-json
    allow_failure: True
    artifacts:
        paths: [ "${PLAN}", ".tfvars" ]
        reports: { terraform: "${PLAN_JSON}" }

Staging:
    stage: Deployment
    image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
    environment: Staging
    when: manual
    needs:
        -   job: Validate (Staging)
            artifacts: True
        -   job: Plan (Staging)
            artifacts: True
    script:
        - export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_DEVELOPMENT}"
        - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_DEVELOPMENT}"

        - export TF_ADDRESS="${TF_URI}/${CI_ENVIRONMENT_NAME}"

        - gitlab-terraform apply

        - gitlab-terraform output --json | jq -r "." > Output.json
        - gitlab-terraform output --json | jq -r ".fqdn.value" > FQDN.UTF-8

        - gitlab-terraform output --json | jq -r ".cdn.value.id" > CDN-ID.UTF-8
        - gitlab-terraform output --json | jq -r ".cdn.value.hosted_zone_id" > CDN-Hosted-Zone-ID.UTF-8
        - gitlab-terraform output --json | jq -r ".cdn.value.fqdn" > CDN-FQDN.UTF-8

        - gitlab-terraform output --json | jq -r ".zone.value.id" > Hosted-Zone-ID.UTF-8
        - gitlab-terraform output --json | jq -r ".zone.value.fqdn" > Hosted-Zone.UTF-8
    artifacts:
        paths:
            - FQDN.UTF-8
            - CDN-ID.UTF-8
            - CDN-Hosted-Zone-ID.UTF-8
            - CDN-FQDN.UTF-8
            - Hosted-Zone-ID.UTF-8
            - Hosted-Zone.UTF-8

Build (Staging):
    image: registry.mycapstone.com/iron-works/node-js-alpine/development/lts
    stage: Build
    environment: Staging
    needs:
        -   job: Repository
            artifacts: True
        -   job: Artifacts
            artifacts: True
    script:
        - mv configuration/.env.staging .env || mv configuration/staging.env .env
        - unzip -o Artifacts.zip && cd Artifacts
        - cp ../.env . && cat .env
        - npm install --production --omit-dev
        - npm run build
    artifacts:
        paths:
            - Artifacts/build

Host-Record (Staging):
    image: registry.mycapstone.com/iron-works/node-js-alpine/production/lts
    stage: DNS
    environment: Staging
    script:
        -   |
            cat << EOF > Provision.json
            {
                "Comment": "Automated Hosted Zone Record",
                "Changes": [
                    {
                        "Action": "CREATE",
                        "ResourceRecordSet": {
                            "Name": "$(cat FQDN.UTF-8)",
                            "Type": "A",
                            "AliasTarget": {
                                "HostedZoneId": "$(cat CDN-Hosted-Zone-ID.UTF-8)",
                                "DNSName": "$(cat CDN-FQDN.UTF-8)",
                                "EvaluateTargetHealth": true
                            }
                        }
                    },
                    {
                        "Action": "CREATE",
                        "ResourceRecordSet": {
                            "Name": "$(cat FQDN.UTF-8)",
                            "Type": "AAAA",
                            "AliasTarget": {
                                "HostedZoneId": "$(cat CDN-Hosted-Zone-ID.UTF-8)",
                                "DNSName": "$(cat CDN-FQDN.UTF-8)",
                                "EvaluateTargetHealth": true
                            }
                        }
                    }
                ]
            }
            EOF
        -   |
            cat << EOF > Update.json
            {
                "Comment": "Automated Hosted Zone Record",
                "Changes": [
                    {
                        "Action": "UPSERT",
                        "ResourceRecordSet": {
                            "Name": "$(cat FQDN.UTF-8)",
                            "Type": "A",
                            "AliasTarget": {
                                "HostedZoneId": "$(cat CDN-Hosted-Zone-ID.UTF-8)",
                                "DNSName": "$(cat CDN-FQDN.UTF-8)",
                                "EvaluateTargetHealth": true
                            }
                        }
                    },
                    {
                        "Action": "UPSERT",
                        "ResourceRecordSet": {
                            "Name": "$(cat FQDN.UTF-8)",
                            "Type": "AAAA",
                            "AliasTarget": {
                                "HostedZoneId": "$(cat CDN-Hosted-Zone-ID.UTF-8)",
                                "DNSName": "$(cat CDN-FQDN.UTF-8)",
                                "EvaluateTargetHealth": true
                            }
                        }
                    }
                ]
            }
            EOF
        -   |
            aws route53 change-resource-record-sets --hosted-zone-id $(cat Hosted-Zone-ID.UTF-8) --change-batch file://Provision.json || true | 2>/dev/null
            aws route53 change-resource-record-sets --hosted-zone-id $(cat Hosted-Zone-ID.UTF-8) --change-batch file://Update.json || true | 2>/dev/null
    artifacts:
        paths:
            - "*.json"
    needs:
        -   job: Validate (Staging)
            artifacts: True
        -   job: Plan (Staging)
            artifacts: True
        -   job: Staging
            artifacts: True

Upload (Staging):
    image: registry.mycapstone.com/iron-works/node-js-alpine/development/lts
    stage: Distribution
    environment: Staging
    script:
        - export TARGET="$(cat FQDN.UTF-8)"
        - aws s3 sync ./Artifacts/build s3://${TARGET}
        - aws s3 sync ./Artifacts/build s3://failover.${TARGET}
    needs:
        -   job: Validate (Staging)
            artifacts: True
        -   job: Plan (Staging)
            artifacts: True
        -   job: Staging
            artifacts: True
        -   job: Build (Staging)
            artifacts: True

Invalidate (Staging):
    stage: CDN
    environment: Staging
    image: registry.mycapstone.com/iron-works/node-js-alpine/development/lts
    script:
        - export TARGET="$(cat CDN-ID.UTF-8)"
        - aws cloudfront create-invalidation --distribution-id "${TARGET}" --paths "/*"
    needs:
        -   job: Validate (Staging)
            artifacts: True
        -   job: Plan (Staging)
            artifacts: True
        -   job: Staging
            artifacts: True
        -   job: Build (Staging)
            artifacts: True
        -   job: Upload (Staging)
            artifacts: True
