import {
    Content,
    Header as CarbonHeader,
    HeaderContainer,
    HeaderGlobalAction,
    HeaderGlobalBar,
    HeaderMenu,
    HeaderMenuButton,
    HeaderMenuItem,
    HeaderName,
    HeaderNavigation,
    HeaderPanel,
    HeaderSideNavItems,
    SideNav,
    SideNavDetails,
    SideNavFooter,
    SideNavHeader,
    SideNavIcon,
    SideNavItem,
    SideNavItems,
    SideNavLink,
    SideNavLinkText,
    SideNavMenu,
    SideNavMenuItem,
    SideNavSwitcher,
    SkipToContent,
    Switcher,
    SwitcherDivider,
    SwitcherItem
} from "carbon-components-react";