AWSTemplateFormatVersion: 2010-09-09
Description: -<
    - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
    - Local Development: -<
        # Invoke Lambda Function with Locally-Defined Environment Variable(s)
        sam local invoke --env-vars env.json
            - The `env.json` schema must key-match the function name
            - Example: -<
                {
                    "Function": {
                        "PASSWORD": "Local-Password-JSON"
                    }
                }

Transform:
    - AWS::Serverless-2016-10-31

Parameters:
    Hostname:
        Description: "..."
        Type: String
        Default: "localhost"
    Username:
        Description: "..."
        Type: String
        Default: "Development"
    Password:
        Default: "Local"
        Description: "..."
        Type: String
        MinLength: 8
        MaxLength: 64
        ConstraintDescription: -<
            The password must be between 8 to 64 characters

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            CodeUri: .
            Runtime: nodejs14.x
            Architectures:
                - x86_64
            MemorySize: 128
            Timeout: 100
            Description: A Lambda Function
            Policies:
                - AWSLambdaBasicExecutionRole
            Environment:
                Variables:
                    HOST: !Ref Hostname
                    USERNAME: !Ref Username
                    PASSWORD: !Ref Password
