AWSTemplateFormatVersion: "2010-09-09"
Description: |
    ...

Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Runtime: "nodejs14.x"
        MemorySize: 128
        Timeout: 30
        Environment:
            Variables:
                AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
    Logging:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub "${AWS::StackName}-Service-Level-Log-Group"

    Administration:
        DependsOn: [ Logging ]
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "Organization", "Environment", "Lambda", "Administration", "Secret-Service" ] ]
            Description: "..."
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            CodeUri: "./packages/administration"
            Policies:
                - AWSLambdaBasicExecutionRole
                -   Version: "2012-10-17"
                    Statement:
                        -   Effect: "Allow"
                            Action:
                                - secretsmanager:GetResourcePolicy
                                - secretsmanager:DescribeSecret
                                - secretsmanager:ListSecretVersionIds
                                - secretsmanager:ListSecrets
                            Resource: "*"
            Events:
                API:
                    Type: HttpApi
                    Properties:
                        Path: /api/administration
                        Method: GET

    List:
        DependsOn: [ Logging ]
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "Organization", "Environment", "Lambda", "List-Secrets", "Secret-Service" ] ]
            Description: "..."
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            CodeUri: "./packages/list-secrets"
            Policies:
                - AWSLambdaBasicExecutionRole
                -   Version: "2012-10-17"
                    Statement:
                        -   Effect: "Allow"
                            Action:
                                - secretsmanager:GetResourcePolicy
                                - secretsmanager:DescribeSecret
                                - secretsmanager:ListSecretVersionIds
                                - secretsmanager:ListSecrets
                            Resource: "*"
            Events:
                API:
                    Type: HttpApi
                    Properties:
                        Path: /api/list-secrets
                        Method: GET

    Get:
        DependsOn: [ Logging ]
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "Organization", "Environment", "Lambda", "Get-Secret", "Secret-Service" ] ]
            Description: "..."
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            CodeUri: "./packages/get-secret"
            Policies:
                - AWSLambdaBasicExecutionRole
                -   Version: "2012-10-17"
                    Statement:
                        -   Effect: "Allow"
                            Action:
                                - secretsmanager:GetResourcePolicy
                                - secretsmanager:DescribeSecret
                                - secretsmanager:ListSecretVersionIds
                                - secretsmanager:ListSecrets
                            Resource: "*"
            Events:
                API:
                    Type: HttpApi
                    Properties:
                        Path: /api/get-secret
                        Method: GET

    Database:
        DependsOn: [ Logging ]
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Join [ "-", [ "Organization", "Environment", "Lambda", "Database", "Example" ] ]
            Description: "..."
            Handler: !Join [ "/", [ "src", "index.handler" ] ]
            CodeUri: "./packages/document-db"
            Policies:
                - AWSLambdaBasicExecutionRole
            Events:
                API:
                    Type: HttpApi
                    Properties:
                        Path: /api/db-connect
                        Method: GET

#    Artifacts:
#        Type: "AWS::Serverless::LayerVersion"
#        Properties:
#            LayerName: Layer
#            Description: Description
#            ContentUri: "Artifacts.zip"
#            RetentionPolicy: Delete
#            CompatibleRuntimes:
#                - nodejs14.x